In [1]:
import torch

## 2.1 Создание нейронов и полносвязных слоев

2.1.1. Используя операции над матрицами и векторами из библиотеки `torch`, реализовать нейрон с заданными весами `weights` и `bias`. Прогнать вектор `inputs` через нейрон и вывести результат. 

In [2]:
import torch

class Neuron:
    def __init__(self, weights, bias):
        # Создаем тензоры для весов и смещения
        self.weights = torch.tensor(weights)
        self.bias = torch.tensor(bias)

    def forward(self, inputs):
        # Умножаем вход на веса, добавляем смещение и применяем активацию (например, сигмоиду)
        result = torch.matmul(self.weights, inputs) + self.bias
        return result

# Пример использования
if __name__ == "__main__":
    weights = [0.5, -0.5]
    bias = 0.2
    neuron = Neuron(weights, bias)
    inputs = torch.tensor([0.3, 0.7])
    output = neuron.forward(inputs)

    print("Результат:", output)


Результат: tensor(1.4901e-08)


In [3]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7])
bias = 3.14

2.1.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой с заданными весами `weights` и `biases`. Прогнать вектор `inputs` через слой и вывести результат. 

In [5]:
import torch

class Linear:
    def init(self, weights, biases):
        self.weights = weights
        self.biases = biases
        
    def forward(self, inputs):
        return torch.matmul(inputs, self.weights) + self.biases
    
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0]).reshape(1, -1)
weights = torch.tensor([-0.2, 0.3, -0.5, 0.7, 0.1, -0.4, 0.6, -0.8, 0.3, -0.5, 0.7, -0.9])
biases = torch.tensor([3.14, 1.5, -2.2])

linearlayer = Linear(weights, biases)
output = linearlayer.forward(inputs)

print(output)

TypeError: Linear() takes no arguments

In [6]:
inputs = torch.tensor([1.0, 2.0, 3.0, 4.0])
weights = torch.tensor([[-0.2, 0.3, -0.5, 0.7],
                        [0.5, -0.91, 0.26, -0.5],
                        [-0.26, -0.27, 0.17, 0.87]]).T

biases = torch.tensor([3.14, 2.71, 7.2])

2.1.3 Реализовать полносвязный слой из __2.1.2__ таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. Продемонстрировать работу.
Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.


In [7]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

2.1.4 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать полносвязный слой из `n_neurons` нейронов с `n_features` весами у каждого нейрона (инициализируются из стандартного нормального распределения). Прогнать вектор `inputs` через слой и вывести результат. Результатом прогона сквозь слой должна быть матрица размера `batch_size` x `n_neurons`.

In [2]:
import torch
import torch.nn as nn

class Linear:
    def __init__(self, n_features, n_neurons):
        # Инициализация весов из стандартного нормального распределения
        self.weights = nn.Parameter(torch.randn(n_features, n_neurons))
        # Инициализация смещений (biases) нулями
        self.biases = nn.Parameter(torch.zeros(n_neurons))

    def forward(self, inputs):
        # Прогоняем входные данные через слой
        # Для этого умножаем входные данные на веса, затем добавляем смещения
        output = torch.matmul(inputs, self.weights) + self.biases
        return output

# Создаем экземпляр слоя с 7 нейронами и 4 входами
n_neurons = 7
n_features = 4
linear_layer = Linear(n_features, n_neurons)

# Создаем вектор inputs
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Прогоняем inputs через слой
output = linear_layer.forward(inputs)

# Выводим результат
print(output)


tensor([[  1.0417,   3.8162,  -9.0545,   1.7390,  -8.5381,  -2.0492,   1.7480],
        [  5.6258,  -0.2470,  -4.1200, -10.0819,  -3.3205,   1.0583,   0.8020],
        [  3.7543,   2.0330,  -5.6896,   1.9437,  -0.1713,   0.9863,  -1.1333]],
       grad_fn=<AddBackward0>)


2.1.5 Используя решение из __2.1.4__, создать 2 полносвязных слоя и пропустить матрицу `inputs` последовательно через эти два слоя. Количество нейронов в первом слое выбрать произвольно, количество нейронов во втором слое выбрать так, чтобы результатом прогона являлась матрица (3x7). 

In [9]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

In [1]:
import torch
import torch.nn as nn

# Создаем матрицу inputs
inputs = torch.tensor([[1, 2, 3, 2.5],
                       [2, 5, -1, 2],
                       [-1.5, 2.7, 3.3, -0.8]])

# Определяем класс модели
class MyModel(nn.Module):
    def __init__(self):
        super(MyModel, self).__init__()
        self.fc1 = nn.Linear(in_features=4, out_features=10)  # Первый полносвязный слой
        self.fc2 = nn.Linear(in_features=10, out_features=7)  # Второй полносвязный слой

    def forward(self, x):
        x = torch.relu(self.fc1(x))  # Применяем ReLU к первому слою
        x = self.fc2(x)  # Второй слой без нелинейности
        return x

# Создаем экземпляр модели
model = MyModel()

# Пропускаем inputs через модель
output = model(inputs)

# Выводим результат
print(output)


tensor([[-4.0196e-01,  1.2120e-01, -2.3489e-01,  2.1246e-01, -2.2733e-02,
          2.8719e-01,  2.2201e-01],
        [-7.5407e-01,  2.4780e-01, -6.6660e-04,  1.2916e-01, -1.1580e-01,
          4.2921e-01,  7.8224e-01],
        [-4.7808e-01,  4.4714e-01, -5.2780e-01,  1.0357e-01,  2.6123e-01,
          1.1584e+00, -2.5004e-02]], grad_fn=<AddmmBackward0>)


## 2.2 Создание функций активации

2.2.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ReLU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/f4353f4e3e484130504049599d2e7b040793e1eb)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [3]:
import torch

class ReLU:
    def forward(self, inputs):
        # Применяем функцию активации ReLU
        return torch.relu(inputs)

# Создаем матрицу размера (4, 3) со случайными числами из стандартного нормального распределения
matrix = torch.randn(4, 3)
relu_activation = ReLU()
result = relu_activation.forward(matrix)
print(result)

tensor([[0.0000, 0.7246, 0.4549],
        [0.0000, 0.7455, 0.0000],
        [0.0000, 0.0000, 0.0000],
        [0.2473, 0.4409, 0.6254]])


2.2.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации softmax:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/6d7500d980c313da83e4117da701bf7c8f1982f5)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации. Строки матрицы трактовать как выходы линейного слоя некоторого классификатора для 4 различных примеров.

In [4]:
import torch
import torch.nn.functional as F

class Softmax:
    def forward(self, inputs):
        # Применяем функцию активации Softmax
        return F.softmax(inputs, dim=-1)

# Создаем матрицу размера (4, 3) со случайными числами из стандартного нормального распределения
matrix = torch.randn(4, 3)
softmax_activation = Softmax()
result = softmax_activation.forward(matrix)
print(result)

tensor([[0.5859, 0.1149, 0.2992],
        [0.1005, 0.1384, 0.7611],
        [0.8251, 0.0685, 0.1065],
        [0.2220, 0.4820, 0.2960]])


2.2.3 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию активации ELU:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/eb23becd37c3602c4838e53f532163279192e4fd)

Создать матрицу размера (4,3), заполненную числами из стандартного нормального распределения, и проверить работоспособность функции активации.

In [5]:
import torch

class ELU:
    def __init__(self, alpha):
        self.alpha = alpha

    def forward(self, inputs):
        # Применяем функцию активации ELU
        return torch.where(inputs > 0, inputs, self.alpha * (torch.exp(inputs) - 1))

# Создаем матрицу размера (4, 3) со случайными числами из стандартного нормального распределения
matrix = torch.randn(4, 3)
elu_activation = ELU(alpha=1.0)  # Здесь alpha - параметр ELU
result = elu_activation.forward(matrix)
print(result)


tensor([[ 0.9554, -0.9370, -0.4796],
        [-0.6708, -0.8166, -0.1695],
        [-0.0393,  0.6921,  0.9509],
        [ 1.3038, -0.7398,  1.3778]])


## 2.3 Создание функции потерь

2.3.1 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь MSE:

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/e258221518869aa1c6561bb75b99476c4734108e)

Создать полносвязный слой с 1 нейроном, прогнать через него батч `inputs` и посчитать значение MSE, трактуя вектор `y` как вектор правильных ответов.

In [6]:
import torch

class MSELoss:
    def forward(self, y_pred, y_true):
        # Рассчитываем среднеквадратичную ошибку
        mse = torch.mean((y_pred - y_true) ** 2)
        return mse

# Создаем полносвязный слой с 1 нейроном
linear_layer = torch.nn.Linear(4, 1)

# Входные данные
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

# Истинные значения
y = torch.tensor([2, 3, 4], dtype=torch.float32)

# Прогоняем входные данные через слой
y_pred = linear_layer(inputs).squeeze()

# Создаем экземпляр функции потерь MSE и вычисляем потерю
mse_loss = MSELoss()
loss = mse_loss.forward(y_pred, y)

print(loss.item())  # Выводим значение MSE


12.325974464416504


In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

y = torch.tensor([2, 3, 4])

2.3.2 Используя операции над матрицами и векторами из библиотеки `torch`, реализовать функцию потерь Categorical Cross-Entropy:

<img src="https://i.ibb.co/93gy1dN/Screenshot-9.png" width="200">

Создать полносвязный слой с 3 нейронами и прогнать через него батч `inputs`. Полученный результат пропустить через функцию активации softmax. Посчитать значение CCE, трактуя вектор `y` как вектор правильных ответов.

In [7]:
import torch
import torch.nn.functional as F

class CategoricalCrossentropyLoss:
    def forward(self, y_pred, y_true):
        # Применяем Softmax к предсказаниям
        y_pred_softmax = F.softmax(y_pred, dim=-1)
        
        # Рассчитываем потерю CCE
        cce_loss = -torch.sum(y_true * torch.log(y_pred_softmax))
        return cce_loss

# Создаем полносвязный слой с 3 нейронами
linear_layer = torch.nn.Linear(4, 3)

# Входные данные
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

# Истинные метки (one-hot encoding)
y = torch.tensor([[0, 1, 0],
                  [1, 0, 0],
                  [1, 0, 0]], dtype=torch.float32)

# Прогоняем входные данные через слой
y_pred = linear_layer(inputs)

# Создаем экземпляр функции потерь CCE и вычисляем потерю
cce_loss = CategoricalCrossentropyLoss()
loss = cce_loss.forward(y_pred, y)

print(loss.item())  # Выводим значение CCE

4.153682231903076


In [ ]:
inputs = torch.tensor([[1, 2, 3, 2.5], 
                        [2, 5, -1, 2], 
                        [-1.5, 2.7, 3.3, -0.8]])
y = torch.tensor([1, 0, 0])

2.3.3 Модифицировать 2.3.1, добавив L2-регуляризацию.

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/d92ca2429275bfdc0474523babbafe014ca8b580)


In [8]:
import torch

class MSELossL2:
    def __init__(self, lambda_):
        self.lambda_ = lambda_

    def data_loss(self, y_pred, y_true):
        # Рассчитываем среднеквадратичную ошибку (MSE)
        mse = torch.mean((y_pred - y_true) ** 2)
        return mse

    def reg_loss(self, layer):
        # Рассчитываем L2-регуляризацию для слоя
        l2_reg = 0.0
        for param in layer.parameters():
            l2_reg += torch.sum(param ** 2)
        return 0.5 * self.lambda_ * l2_reg

    def forward(self, y_pred, y_true, layer):
        data_loss = self.data_loss(y_pred, y_true)
        reg_loss = self.reg_loss(layer)
        return data_loss + reg_loss

# Создаем полносвязный слой с 1 нейроном
linear_layer = torch.nn.Linear(4, 1)

# Входные данные
inputs = torch.tensor([[1, 2, 3, 2.5], 
                       [2, 5, -1, 2], 
                       [-1.5, 2.7, 3.3, -0.8]])

# Истинные значения
y = torch.tensor([2, 3, 4], dtype=torch.float32)

# Прогоняем входные данные через слой
y_pred = linear_layer(inputs).squeeze()

# Создаем экземпляр функции потерь MSE с L2-регуляризацией и вычисляем потерю
mse_loss_l2 = MSELossL2(lambda_=0.01)  # Здесь lambda - коэффициент регуляризации
loss = mse_loss_l2.forward(y_pred, y, linear_layer)

print(loss.item())  # Выводим значение MSE с L2-регуляризацией


2.1336112022399902


## 2.4 Обратное распространение ошибки

2.4.1 Используя один нейрон и SGD (1 пример за шаг), решите задачу регрессии

In [9]:
from sklearn.datasets import make_regression

X, y, coef = make_regression(n_features=4, n_informative=4, coef=True, bias=0.5)
X = torch.from_numpy(X).to(torch.float32)
y = torch.from_numpy(y).to(torch.float32)

In [10]:
X.size()

torch.Size([100, 4])

[Граф вычислений для этой задачи](https://i.ibb.co/2dhDxZx/photo-2021-02-15-17-18-04.jpg)

2.4.1.1 Реализуйте класс `SquaredLoss`


In [ ]:
class SquaredLoss:
  def forward(self, y_pred, y_true):
    return # <реализовать логику MSE>

  def backward(self, y_pred, y_true):
    self.dinput = # df/dc


2.4.1.2. Модифицируйте класс `Neuron` из __2.1.1__:

  1) Сделайте так, чтобы веса нейрона инициализировались из стандартного нормального распределения

  2) Реализуйте расчет градиента относительно весов `weights` и `bias`

In [23]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.b = torch.randn(1)
    self.w = torch.randn(n_features)
    pass
  
  def forward(self, inputs):
    self.inputs = inputs
    y_pred = torch.dot(inputs, self.w)+self.b
    return  y_pred
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss
    
    self.dw = dvalue*self.inputs # df/dW
    self.db = dvalue*1 # dE/b = de/dy_pred * dy_pred/db


2.4.1.3 Допишите цикл для настройки весов нейрона

[SGD](https://ru.wikipedia.org/wiki/%D0%A1%D1%82%D0%BE%D1%85%D0%B0%D1%81%D1%82%D0%B8%D1%87%D0%B5%D1%81%D0%BA%D0%B8%D0%B9_%D0%B3%D1%80%D0%B0%D0%B4%D0%B8%D0%B5%D0%BD%D1%82%D0%BD%D1%8B%D0%B9_%D1%81%D0%BF%D1%83%D1%81%D0%BA)

![](https://wikimedia.org/api/rest_v1/media/math/render/svg/dda3670f8a8996a0d3bf80856bb4a166cc8db6d4)

In [24]:
n_inputs = X.size()[1]# <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 10 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()

losses = []
for epoch in range(100):
  for x_example, y_example in zip(X, y):
    # forward pass
    y_pred = neuron.forward(x_example)
    curr_loss = loss.forward(y_pred, y_example)
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    loss.backward(y_pred, y_example)
    neuron.backward(loss.dvalue)
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>
    neuron.w -= learning_rate*neuron.dw
    neuron.b -= learning_rate*neuron.db

2.4.2 Решите задачу 2.4.1, используя пакетный градиентный спуск

Вычисления для этой задачи: 
[1](https://i.ibb.co/rmtQT6P/photo-2021-02-15-18-00-43.jpg)
[2](https://i.ibb.co/NmCFVnQ/photo-2021-02-15-18-01-17.jpg)

2.4.1.1 Модифицируйте класс `MSELoss` из __2.3.1__, реализовав расчет производной относительно предыдущего слоя с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами
 

In [13]:
class MSELoss:
  def forward(self, y_pred, y_true):
    return (y_pred-y_true)**2

  def backward(self, y_pred, y_true):
    self.dvalue = 2*(y_pred-y_true)   # здесь интегрируются атрибуты класса


2.4.2.2. Модифицируйте класс `Neuron` из __2.4.1.2__:

  1) Реализуйте метод `forward` таким образом, чтобы он мог принимать на вход матрицу (батч) с данными. 

  2) Реализуйте расчет градиента относительно весов `weights` и `bias` с учетом того, что теперь работа ведется с батчами, а не с индивидуальными примерами

In [14]:
class Neuron:
  def __init__(self, n_inputs):
    # <создать атрибуты объекта weights и bias>
    self.b = torch.randn(1)
    self.w = to rch.randn(n_features)
    pass
  
  def forward(self, inputs):
    self.inputs = inputs
    y_pred = torch.dot(inputs, self.w)+self.b
    return # <реализовать логику нейрона>
  
  def backward(self, dvalue):
    # dvalue - значение градиента, которое приходит нейрону от следующего слоя сети
    # в данном случае это будет градиент L по y^ (созданный методом backwards у объекта MSELoss
    
    self.dweights = dvalue*self.inputs # df/dW
    self.dbias = dvalue*1 # dE/b = de/dy_pred * dy_pred/db


2.4.2.3 Допишите цикл для настройки весов нейрона

In [ ]:
n_inputs = # <размерность элемента выборки >
learning_rate = 0.1 #  скорость обучения
n_epoch = 100 #  количество эпох

neuron = Neuron(n_inputs)
loss = MSELoss()


for epoch in range(100):
    # forward pass
    y_pred = # <прогон через нейрон>
    curr_loss = # <прогон через функцию потерь>
    losses.append(curr_loss)

    # backprop
    # <вызов методов backward>
    # обратите внимание на последовательность вызовов: от конца к началу

    # <шаг оптимизации для весов (weights и bias) нейрона>

2.4.3  Используя один полносвязный слой и  пакетный градиетный спуск, решите задачу регрессии из __2.4.1__

2.4.3.1 Модифицируйте класс `Linear` из __2.1.4__. ([вычисление градиентов](https://i.ibb.co/kgVR6m6/photo-2021-02-15-21-30-28.jpg))

In [ ]:
class Linear:
  def __init__(self, n_features, n_neurons):
    # <создать атрибуты объекта weights и biases>
    pass
  
  def forward(self, inputs):
    return # <реализовать логику слоя>

  def backward(self, dvalues):
    self.dweights = # df/dW
    self.dbiases = # df/db
    self.dinputs = # df/dX

2.4.3.2 Создайте слой с одним нейроном. Используя класс MSELoss из 2.4.2, убедитесь, что модель обучается

2.4.4 Используя наработки из 2.4, создайте нейросеть и решите задачу регрессии.

Предлагаемая архитектура: 
1. Полносвязный слой с 10 нейронами
2. Активация ReLU
3. Полносвязный слой с 1 нейроном

In [ ]:
X = torch.linspace(-1, 1, 100).view(-1, 1)
y = X.pow(2) + 0.2 * torch.rand(X.size()) 

In [ ]:
class Activation_ReLU:
  def forward(self, inputs):
    self.inputs = inputs
    self.output = inputs.clip(min=0)
    return self.output
  
  def backward(self, dvalues):
    self.dinputs = dvalues.clone()
    self.dinputs[self.inputs <= 0] = 0

In [ ]:
# создание компонентов сети
# fc1 = 
# relu1 = 
# fc2 = 

loss = MSELoss()
lr = 0.02

ys = []
for epoch in range(2001):
  # <forward pass>
  # fc1 > relu1 > fc2 > loss

  data_loss = # <прогон через функцию потерь>

  if epoch % 200 == 0:
    print(f'epoch {epoch} mean loss {data_loss}')
    ys.append(out)
  
  # <backprop> 
  # loss > fc2 > relu1 > fc1

  # <шаг оптимизации для fc1>

  # <шаг оптимизации для fc2>


In [ ]:
import matplotlib.pyplot as plt

fig, axs = plt.subplots(len(ys), 1, figsize=(10, 40))
for ax, y_ in zip(axs, ys):
  ax.scatter(X.numpy(), y.numpy(), color = "orange")
  ax.plot(X.numpy(), y_.numpy(), 'g-', lw=3)
  ax.set_xlim(-1.05, 1.5)
  ax.set_ylim(-0.25, 1.25)